server:
  port: 8080
spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    discovery:
      enabled: true
      client:
        simple:
          instances:
            iste-artifact:
              - uri: http://localhost:2020
                serviceId: iste-artifact
logging:
  level:
    root: INFO
