server:
  port: 8080

feign:
  httpclient:
    hc5:
      enabled: true
  hystrix:
    enabled: false
  client:
    config:
      default:
        connect-timeout: 3000
        read-timeout: 5000
        logger-level: full

resilience4j:
  circuitbreaker:
    instances:
      iste-artifact:
        registerHealthIndicator: true
        slidingWindowSize: 10
  retry:
    instances:
      iste-artifact:
        maxRetryAttempts: 3
        waitDuration: 500ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    discovery:
      enabled: true
      client:
        simple:
          instances:
            iste-artifact:
              - uri: http://localhost:8080
                serviceId: iste-artifact
logging:
  level:
    root: INFO
